################################################################################
# RTAS generated configuration dependencies
################################################################################

ifneq ($(strip $(OBJS)),)
$(OBJS): $(RTAS_GENERATED_CONFIG)
endif
